name: Deploy Pull Request to main Environment

on:
  push:
    branches: [main]

jobs:
  build_docker_image:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    outputs:
      image_tag: ${{ steps.meta.outputs.tags }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: edit .env file
        env:
          PORT: ${{ secrets.PORT }}
          HOST: ${{ secrets.HOST }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          REDIS_URL: ${{ secrets.REDIS_URL }}
          KAFKA_BROKER: ${{ secrets.KAFKA_BROKER }}
          KAFKA_CLIENT_ID: ${{ secrets.KAFKA_CLIENT_ID }}
          KAFKA_TOPIC_LOGOUT: ${{ secrets.KAFKA_TOPIC_LOGOUT }}
          KAFKA_TOPIC_LOGIN: ${{ secrets.KAFKA_TOPIC_LOGIN }}
          ENCRYPTION_KEY: ${{ secrets.ENCRYPTION_KEY }}
          ENCRYPTION_IV: ${{ secrets.ENCRYPTION_IV }}
        run: |
          echo "PORT=${PORT}" > .env
          echo "JWT_SECRET=${JWT_SECRET}" >> .env
          echo "REDIS_URL=${REDIS_URL}" >> .env
          echo "REDIS_PORT=${REDIS_PORT}" >> .env
          echo "KAFKA_BROKER=${KAFKA_BROKER}" >> .env
          echo "KAFKA_CLIENT_ID=${KAFKA_CLIENT_ID}" >> .env
          echo "KAFKA_TOPIC_LOGOUT=${KAFKA_TOPIC_LOGOUT}" >> .env
          echo "KAFKA_TOPIC_LOGIN=${KAFKA_TOPIC_LOGIN}" >> .env
          echo "ENCRYPTION_KEY=${ENCRYPTION_KEY}" >> .env
          echo "ENCRYPTION_IV=${ENCRYPTION_IV}" >> .env

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker Hub logout
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: byvoxel/auth-logout
          tags: |
            type=raw,value=staging
          
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: byvoxel/auth-logout:staging
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy_to_ec2:
    name: Deploy to EC2 Instances
    runs-on: ubuntu-latest
    needs: build_docker_image
    strategy:
      matrix:
        ec2_instance: 
          - ec2-18-214-162-122.compute-1.amazonaws.com

    steps:
      - name: Deploy Container
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ matrix.ec2_instance }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          timeout: "120s"
          script: |
            set -e
            echo "Deploying image: byvoxel/auth-logout:staging"
            sudo docker stop auth-logout || true
            sudo docker rm auth-logout || true
            sudo docker pull byvoxel/auth-logout:staging
            sudo docker run -d \
              --name auth-logout \
              -p 3011:3011 \
              --restart unless-stopped \
              byvoxel/auth-logout:staging
            sudo docker system prune -af --volumes || true